#!/usr/bin/env python3
"""
Download Google Fonts for offline/self-hosted use.

Generates:
  - assets/fonts/*.woff2 — font files
  - css/fonts-local.css — @font-face declarations

Usage:
    python scripts/download_fonts.py

After running, replace the Google Fonts <link> in HTML files with:
    <link rel="stylesheet" href="css/fonts-local.css" />
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from urllib.request import urlopen, Request
from urllib.error import URLError

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "assets" / "fonts"
CSS_OUT = ROOT / "css" / "fonts-local.css"

# Google Fonts CSS API v2 — request woff2 format
GOOGLE_FONTS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Space+Grotesk:wght@400;500;600;700"
    "&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700"
    "&family=Noto+Sans+SC:wght@300;400;500;600;700"
    "&family=Noto+Serif+SC:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500;600"
    "&display=swap"
)

# User-Agent tricks Google into returning woff2 URLs
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)


def fetch_css() -> str:
    """Fetch the Google Fonts CSS (with woff2 URLs)."""
    req = Request(GOOGLE_FONTS_URL, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def download_font(url: str, dest: Path) -> None:
    """Download a single font file."""
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=60) as resp:
        dest.write_bytes(resp.read())


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)

    print("Fetching Google Fonts CSS...")
    try:
        css = fetch_css()
    except URLError as e:
        print(f"ERROR: Could not fetch fonts — {e}")
        print("Check your network connection. Fonts will fall back to CDN.")
        sys.exit(1)

    # Parse @font-face blocks and download woff2 files
    import re
    font_faces = re.findall(r'@font-face\s*\{[^}]+\}', css, re.DOTALL)
    local_css_parts = []
    downloaded = set()

    for face in font_faces:
        # Extract url
        url_match = re.search(r'url\((https://[^\)]+\.woff2)\)', face)
        if not url_match:
            local_css_parts.append(face)
            continue

        url = url_match.group(1)
        filename = url.split("/")[-1].split("?")[0]

        if filename not in downloaded:
            dest = FONTS_DIR / filename
            if not dest.exists():
                print(f"  Downloading {filename}...")
                try:
                    download_font(url, dest)
                except URLError as e:
                    print(f"  WARNING: Failed to download {filename}: {e}")
                    local_css_parts.append(face)
                    continue
            downloaded.add(filename)

        # Replace remote URL with local path
        local_face = face.replace(url, f"../assets/fonts/{filename}")
        local_css_parts.append(local_face)

    # Write local CSS
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text(
        "/* Auto-generated by scripts/download_fonts.py — DO NOT EDIT */\n"
        "/* Replace Google Fonts <link> with: <link rel=\"stylesheet\" href=\"css/fonts-local.css\" /> */\n\n"
        + "\n\n".join(local_css_parts)
        + "\n",
        encoding="utf-8"
    )

    print(f"\nDownloaded {len(downloaded)} font files to {FONTS_DIR}/")
    print(f"Generated {CSS_OUT}")
    print(f"\nTo use: replace the Google Fonts <link> in your HTML with:")
    print(f'  <link rel="stylesheet" href="css/fonts-local.css" />')


if __name__ == "__main__":
    main()
